; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28316.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\iMeG\AppData\Local\Temp\.NETCoreApp,Version=v3.1.AssemblyAttributes.cpp"
